# -*- coding: utf-8 -*-
"""Canonical CSV output naming and alias normalization utilities."""


def get_available_csv_outputs():
    return {
        'data.csv': 'Main simulation time-series',
        'active_stress_data.csv': 'Active stress at integration points',
        'alpha_f_data.csv': 'Myofiber stretch alpha_f',
        'bulk_passive_data.csv': 'Bulk passive stress',
        'Ca_content_data.csv': 'Calcium content',
        'Ca_cytosol_data.csv': 'Cytosolic calcium',
        'Ca_SR_data.csv': 'SR calcium',
        'cb_number_density_data.csv': 'Cross-bridge number density',
        'cb_stress_data.csv': 'Cross-bridge stress',
        'dx_data.csv': 'Displacement x',
        'dy_data.csv': 'Displacement y',
        'dz_data.csv': 'Displacement z',
        'Ecc_data.csv': 'Green-Lagrange circumferential strain',
        'eccx_data.csv': 'Circumferential direction x',
        'eccy_data.csv': 'Circumferential direction y',
        'eccz_data.csv': 'Circumferential direction z',
        'Ell_data.csv': 'Green-Lagrange longitudinal strain',
        'ellx_data.csv': 'Longitudinal direction x',
        'elly_data.csv': 'Longitudinal direction y',
        'ellz_data.csv': 'Longitudinal direction z',
        'endo_dist_data.csv': 'Endocardial distance',
        'Err_data.csv': 'Green-Lagrange radial strain',
        'errx_data.csv': 'Radial direction x',
        'erry_data.csv': 'Radial direction y',
        'errz_data.csv': 'Radial direction z',
        'ext_passive_exp_L_data.csv': 'External passive exponential L',
        'ext_passive_exp_sigma_data.csv': 'External passive exponential sigma',
        'ext_passive_l_slack_data.csv': 'External passive slack length',
        'f01_data.csv': 'Fiber direction x-component',
        'f02_data.csv': 'Fiber direction y-component',
        'f03_data.csv': 'Fiber direction z-component',
        'fiber_strain_data.csv': 'Fiber strain',
        'fr_angle_data.csv': 'Fiber reorientation angle',
        'gr_deviation_fiber_data.csv': 'Growth deviation (fiber)',
        'gr_deviation_sheet_data.csv': 'Growth deviation (sheet)',
        'gr_deviation_sheet_normal_data.csv': 'Growth deviation (sheet normal)',
        'gr_global_theta_fiber_data.csv': 'Growth global theta (fiber)',
        'gr_global_theta_sheet_data.csv': 'Growth global theta (sheet)',
        'gr_global_theta_sheet_normal_data.csv': 'Growth global theta (sheet normal)',
        'gr_local_theta_fiber_data.csv': 'Growth local theta (fiber)',
        'gr_local_theta_sheet_data.csv': 'Growth local theta (sheet)',
        'gr_local_theta_sheet_normal_data.csv': 'Growth local theta (sheet normal)',
        'gr_setpoint_fiber_data.csv': 'Growth setpoint (fiber)',
        'gr_setpoint_sheet_data.csv': 'Growth setpoint (sheet)',
        'gr_setpoint_sheet_normal_data.csv': 'Growth setpoint (sheet normal)',
        'gr_stimulus_fiber_data.csv': 'Growth stimulus (fiber)',
        'gr_stimulus_sheet_data.csv': 'Growth stimulus (sheet)',
        'gr_stimulus_sheet_normal_data.csv': 'Growth stimulus (sheet normal)',
        'hs_length_data.csv': 'Half-sarcomere length',
        'incomp_stress_data.csv': 'Incompressibility stress',
        'int_passive_exp_L_data.csv': 'Internal passive exponential L',
        'int_passive_exp_sigma_data.csv': 'Internal passive exponential sigma',
        'int_passive_l_slack_data.csv': 'Internal passive slack length',
        'J_1_data.csv': 'Flux J_1',
        'J_2_data.csv': 'Flux J_2',
        'J_3_data.csv': 'Flux J_3',
        'J_4_data.csv': 'Flux J_4',
        'J_off_data.csv': 'Flux J_off',
        'J_on_data.csv': 'Flux J_on',
        'J_release_data.csv': 'Flux J_release',
        'J_uptake_data.csv': 'Flux J_uptake',
        'k_1_data.csv': 'Rate k_1',
        'k_2_data.csv': 'Rate k_2',
        'k_3_data.csv': 'Rate k_3',
        'k_4_0_data.csv': 'Rate k_4_0',
        'k_4_1_data.csv': 'Rate k_4_1',
        'k_act_data.csv': 'Rate k_act',
        'k_cb_data.csv': 'Rate k_cb',
        'k_coop_data.csv': 'Rate k_coop',
        'k_force_data.csv': 'Rate k_force',
        'k_leak_data.csv': 'Rate k_leak',
        'k_off_data.csv': 'Rate k_off',
        'k_on_data.csv': 'Rate k_on',
        'k_serca_data.csv': 'Rate k_serca',
        'lx_data.csv': 'Local coordinate x',
        'ly_data.csv': 'Local coordinate y',
        'lz_data.csv': 'Local coordinate z',
        'M_DRX_data.csv': 'Myofilament state M_DRX',
        'M_FG_data.csv': 'Myofilament state M_FG',
        'M_SRX_data.csv': 'Myofilament state M_SRX',
        'membrane_activation_data.csv': 'Membrane activation',
        'myofiber_passive_data.csv': 'Myofiber passive stress',
        'n_bound_data.csv': 'n_bound',
        'n_off_data.csv': 'n_off',
        'n_on_data.csv': 'n_on',
        'n_overlap_data.csv': 'n_overlap',
        'pas_stress_data.csv': 'Passive stress',
        'prop_fibrosis_data.csv': 'Fibrosis proportion',
        'prop_myofilaments_data.csv': 'Myofilaments proportion',
        'Sff_data.csv': 'Sff',
        'sff_mean_data.csv': 'Mean Sff',
        'Sff_mesh_data.csv': 'Sff projected to mesh',
        'slack_hs_length_data.csv': 'Slack half-sarcomere length',
        't_act_left_data.csv': 'Left activation time',
        't_open_data.csv': 'Open time',
        'total_passive_data.csv': 'Total passive stress',
        'total_stress_data.csv': 'Total stress',
        'total_stress_spatial_data.csv': 'Total stress spatial',
        'x_ps_data.csv': 'x_ps state',
        'spatialdata.csv': 'All spatial fields averaged across integration points',
    }


def get_output_alias_map():
    aliases = {
        'activestressdata.csv': 'active_stress_data.csv',
        'alphafdata.csv': 'alpha_f_data.csv',
        'bulkpassivedata.csv': 'bulk_passive_data.csv',
        'cbnumberdensitydata.csv': 'cb_number_density_data.csv',
        'cbstressdata.csv': 'cb_stress_data.csv',
        'dxdata.csv': 'dx_data.csv',
        'dydata.csv': 'dy_data.csv',
        'dzdata.csv': 'dz_data.csv',
        'Eccdata.csv': 'Ecc_data.csv',
        'eccxdata.csv': 'eccx_data.csv',
        'eccydata.csv': 'eccy_data.csv',
        'ecczdata.csv': 'eccz_data.csv',
        'Elldata.csv': 'Ell_data.csv',
        'ellxdata.csv': 'ellx_data.csv',
        'ellydata.csv': 'elly_data.csv',
        'ellzdata.csv': 'ellz_data.csv',
        'endodistdata.csv': 'endo_dist_data.csv',
        'Errdata.csv': 'Err_data.csv',
        'errxdata.csv': 'errx_data.csv',
        'errydata.csv': 'erry_data.csv',
        'errzdata.csv': 'errz_data.csv',
        'f01data.csv': 'f01_data.csv',
        'f02data.csv': 'f02_data.csv',
        'f03data.csv': 'f03_data.csv',
        'fiberstraindata.csv': 'fiber_strain_data.csv',
        'frangledata.csv': 'fr_angle_data.csv',
        'hslengthdata.csv': 'hs_length_data.csv',
        'incompstressdata.csv': 'incomp_stress_data.csv',
        'k1data.csv': 'k_1_data.csv',
        'k2data.csv': 'k_2_data.csv',
        'k3data.csv': 'k_3_data.csv',
        'k4_0data.csv': 'k_4_0_data.csv',
        'k4_1data.csv': 'k_4_1_data.csv',
        'kactdata.csv': 'k_act_data.csv',
        'kcbdata.csv': 'k_cb_data.csv',
        'kcoopdata.csv': 'k_coop_data.csv',
        'kforcedata.csv': 'k_force_data.csv',
        'kleakdata.csv': 'k_leak_data.csv',
        'koffdata.csv': 'k_off_data.csv',
        'kondata.csv': 'k_on_data.csv',
        'ksercadata.csv': 'k_serca_data.csv',
        'lxdata.csv': 'lx_data.csv',
        'lydata.csv': 'ly_data.csv',
        'lzdata.csv': 'lz_data.csv',
        'myofiberpassivedata.csv': 'myofiber_passive_data.csv',
        'passtressdata.csv': 'pas_stress_data.csv',
        'Sffdata.csv': 'Sff_data.csv',
        'Sffmeshdata.csv': 'Sff_mesh_data.csv',
        'totalpassivedata.csv': 'total_passive_data.csv',
        'totalstressdata.csv': 'total_stress_data.csv',
        'xpsdata.csv': 'x_ps_data.csv',
        'data.xlsx': 'data.csv',
        'spatialdata.xlsx': 'spatialdata.csv',
        'spatialaverage.xlsx': 'spatialdata.csv',
        'spatial_average.csv': 'spatialdata.csv',
        'spatial_average.xlsx': 'spatialdata.csv',
    }
    return aliases


def normalize_output_name(name):
    aliases = get_output_alias_map()
    return aliases.get(name, name)
