# -*- coding: utf-8 -*-

"""

Created on Mon Jan 10 11:15:59 2022

@author: Hossein

Modified: February 2026 - Added JSON-controlled output system

"""

from ast import operator
from operator import methodcaller
import os
import json
import math
import pandas as pd
import numpy as np
from dolfin import *
import time
from protocol import protocol as prot
from .dependencies.recode_dictionary import recode
from .mesh.mesh import MeshClass
from .circulation.circulation import Circulation as circ
from .heart_rate.heart_rate import heart_rate as hr
from .dependencies.forms import Forms
from .dependencies.nsolver import NSolver
from .output_handler.output_handler import output_handler as oh
from .baroreflex import baroreflex as br
from .growth import growth as gr
from .half_sarcomere import half_sarcomere as hs
from .fiber_reorientation import fiber_reorientation as fr
from .dependencies.assign_local_coordinate_system import assign_local_coordinate_system as lcs
from mpi4py import MPI

class LV_simulation():
    """Class for running a LV simulation using FEniCS"""

    def __init__(self,comm, instruction_data):

        self.spatial_gr_data_fields = []
        self.spatial_myof_data_fields = []
        self.spatial_memb_data_fields = []
        self.spatial_hs_data_fields = []
        self.spatial_fiber_data_fields = []
        self.spatial_extra = []
        self.f0_values = []
        self.fdiff_values = []
        self.lcoord_values = []
        self.f_proj_value = []
        self.f_proj_CG_value = []
        self.traction_vector_value = []

        # Check for model input first
        if not "model" in instruction_data:
            return

        self.instruction_data = instruction_data

        # Create a model dict for things that do not change during a simulation
        self.model = dict()

        # And a data dict for things that might
        self.data = dict()

        # Create the comminicator between cores
        self.comm = comm

        # Define half_sarcomere class to be used in initilizing
        # function spaces, functions, and week form
        hs_struct = instruction_data['model']['half_sarcomere']
        self.hs = hs.half_sarcomere(hs_struct)
        self.y_vec_length = len(self.hs.myof.y)

        # Initialize and define mesh objects (finite elements,
        # function spaces, functions)
        self.mesh = MeshClass(self)

        # Initialize the solver object
        self.solver = NSolver(self,self.mesh,comm)

        self.y_vec = self.mesh.model['functions']['y_vec'].vector().get_local()[:]

        self.initialize_dof_mapping()

        if self.comm.Get_rank() == 0:
            print 'dof mapping on core 0'
            print self.dofmap

        self.initialize_integer_points()

        """ Create a data structure for holding """
        # half_sarcomere parameters spatially
        # 4 comes from using degree 2
        self.local_n_of_int_points = 4 * np.shape(self.mesh.model['mesh'].cells())[0]

        """ Calculate the total no of integration points"""
        # First on the root core
        self.global_n_of_int_points = self.comm.reduce(self.local_n_of_int_points)

        # Then broadcast to all other cores
        self.global_n_of_int_points = self.comm.bcast(self.global_n_of_int_points)

        """ Now generate a list (with len = total num of cores) """
        # that holds the num of integer points for each core
        self.int_points_per_core = np.zeros(self.comm.Get_size())

        # Send local num of integer points to root core (i.e. 0)
        if self.comm.Get_rank() != 0:
            self.comm.send(self.local_n_of_int_points,dest = 0, tag = 1)
        else: # Root core recieves local num of int points from other cores
            self.int_points_per_core[0] = self.local_n_of_int_points
            for i in range(1,self.comm.Get_size()):
                self.int_points_per_core[i] = self.comm.recv(source = i, tag = 1)

        # Now broadcast the list to all cores
        self.int_points_per_core = self.comm.bcast(self.int_points_per_core)

        if self.comm.Get_rank() == 1:
            print 'Total no if int points is %0.0f' % self.global_n_of_int_points

        """ Generating arrays for holding half-sarcomere data"""
        # accross the mesh
        # Start with half-saromere length
        self.hs_length_list = self.mesh.hs_length_list

        # Delta half-sarcomere length
        self.delta_hs_length_list = np.zeros(self.local_n_of_int_points)

        # Active stress generated by cross-bridge cycling of myosin
        self.cb_stress_list = self.mesh.cb_stress_list

        # Passive stress in half-sarcomeres
        self.pass_stress_list = self.mesh.pass_stress_list

        """ Generating half-sarcomere object list"""
        self.hs_objs_list = []

        for i in np.arange(self.local_n_of_int_points):
            self.hs_objs_list.append(hs.half_sarcomere(hs_struct))
            self.hs_objs_list[-1].data['hs_length'] = self.hs_length_list[i]

        #### MM here we assign het params to the LV
        for key in ['k_1','k_3','k_on','cb_number_density','k_cb','x_ps']:
            dolfin_function = self.mesh.model['functions']['dolfin_functions'].get(key, None)
            if dolfin_function is None:
                continue
            dolfin_values = dolfin_function[-1].vector().get_local()
            for i in range(self.local_n_of_int_points):
                self.hs_objs_list[i].myof.data[key] = dolfin_values[i]

        """ Handle the coordinates of quadrature (integer) points"""
        gdim = self.mesh.model['mesh'].geometry().dim()
        self.coord = self.mesh.model['function_spaces']['quadrature_space'].tabulat_dof_coordinates().reshape((-1, gdim))

        if self.comm.Get_rank()!=0:
            self.comm.send(self.coord,dest=0,tag = 3)
        else:
            for i in range(1,self.comm.Get_size()):
                self.coord = np.append(self.coord, self.comm.recv(source = i, tag = 3),axis = 0)

        self.handle_coordinates_of_geometry()
        self.handle_apex_contractility(instruction_data)
        self.handle_hs_visualization_on_mesh()

        # now build an array for storing radius of apex for local integer points
        self.apex_r_local = np.zeros(self.local_n_of_int_points)
        for i,j in enumerate(self.dofmap):
            self.apex_r_local[i] = self.apex_r[j]

